development:
  adapter: postgresql
  encoding: unicode
  database: school

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: school
  pool: 5
  username: schoolportal
  password: school

