development:
  adapter: postgresql
  encoding: unicode
  database: school_dev


production:
  adapter: postgresql
  encoding: unicode
  host: 10.10.2.14
  database: school
  pool: 5
  username: schoolportal
  password: school

